### ISSUE TITLE
Pepper Spray is not working correctly when more than 1 is equipped with you.

### ISSUE THREAD

**Issue by TheSuggester** [EFdee-BTLA/SEF_BTLA#10]
In SEF 7.0, when you finish using Pepper Spray, the game automatically switches to a full bottle if you have another one equipped with you.

However, in this mod, attempting to do so will equip the empty bottle (that you just used) with no way to switch to a new Pepper Spray.

Can this issue be fixed?

**Comment by EFdee-BTLA** [comment]
Wasn't aware of this, i'll take a look at it. Thanks for the report!

**Comment by EFdee-BTLA** [comment]
Fixed

**Comment by EFdee-BTLA** [comment]
Fixed
