### ISSUE TITLE
When using a semi-auto shotgun (even with 12 Gauge Frangible equipped), the "Fire: Breach Door" does not appear.

### ISSUE THREAD

**Issue by TheSuggester** [EFdee-BTLA/SEF_BTLA#11]
When using a semi-auto shotgun (even with 12 Gauge Frangible equipped), the "Fire: Breach Door" does not appear.

Instead, it is replaced with "Fire: (Hold) Lock door".

Can this issue be resolved so that players can breach doors with semi-auto shotguns?

**(DISCLAIMER: The first two images are with a semi-auto shotgun while the other 2 are with a pump-action shotgun (that does not have a breaching nozzle) equipped.)**

![swat4x 2021-07-06 16-58-42-896](https://user-images.githubusercontent.com/38480961/124666259-c86f1980-de7b-11eb-84fa-fdf4f178b409.jpg)
![swat4x 2021-07-06 16-58-59-666](https://user-images.githubusercontent.com/38480961/124666262-ca38dd00-de7b-11eb-8550-19b217e1956c.jpg)
![swat4x 2021-07-06 16-59-16-133](https://user-images.githubusercontent.com/38480961/124666264-ca38dd00-de7b-11eb-8adf-2913f2d03dcb.jpg)
![swat4x 2021-07-06 16-59-28-594](https://user-images.githubusercontent.com/38480961/124666266-ca38dd00-de7b-11eb-880a-0a3cf28b6532.jpg)

**Comment by EFdee-BTLA** [comment]
Indeed, this bug it's SEF legacy, im not entirely sure why it happens because every shotgun is a child of the Main ShotgunBase class. i'll take a look at it at some point.

**Comment by EFdee-BTLA** [comment]
Fixed
