### ISSUE TITLE
I have posted Beta 3 here so people can download it without needing to create a Discord account.

### ISSUE THREAD

**Issue by TheSuggester** [EFdee-BTLA/SEF_BTLA#20]
SWAT - Back To Los Angeles: Close Quarters Battle Version 1.4 Beta 3 has arrived!! Make sure to perform a clean installation of the mod (Delete your old SEF-BTLA folder and add the new one) Make sure to check the changelog. 

https://drive.google.com/file/d/11-vrOhWLtbSVUBTuQSfxYYutYo4VvuUc/view?usp=sharing

UPDATE: Added mirrors (Thanks S4)

EU: http://swat4.tk/download/mods/SEF-BTLA%20v1.4%20Beta%203.zip

US East: http://108.61.155.147/SEF-BTLA%20v1.4%20Beta%203.zip

**Comment by Masterscape** [comment]
bruh

**Comment by Masterscape** [comment]
Beta 4 is made TO BE exclusive to the discord

**Comment by MightyBalls6** [comment]
![image](https://user-images.githubusercontent.com/26145794/130516230-cd3eed97-942a-4baf-a383-3ce1bac989d4.png)

**Comment by Masterscape** [comment]
EFdee could've just put it on ModDB if it was a release

**Comment by Masterscape** [comment]
Delete it you sausage

**Comment by TheSuggester** [comment]
Should I delete this then? I'm going to a place that IP bans Discord but not GitHub.
